// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationCheck.Data;

#nullable disable

namespace StationCheck.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130220000_RemoveUserIdFromUserDevice")]
    partial class RemoveUserIdFromUserDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Include the rest of the model configuration here
#pragma warning restore 612, 618
        }
    }
}
