// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationCheck.Data;

#nullable disable

namespace StationCheck.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118041210_AddSoftDeleteAndAuditFields")]
    partial class AddSoftDeleteAndAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationCheck.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId1")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId1");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "USR001",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 622, DateTimeKind.Utc).AddTicks(599),
                            Email = "admin@stationcheck.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$12$ji4FH.1gJgNCQcZXKH0YGOY1ILZiO0U7ypmjN2By8eH1ve3wbLbu.",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = "USR002",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 622, DateTimeKind.Utc).AddTicks(603),
                            Email = "manager@stationcheck.com",
                            FullName = "Department Manager",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$12$HAIqn7gev23sgk0k3AM2JesgtSM7jgq7eVjd5kPGD4N4CMBI7Vd6y",
                            Role = 1,
                            Username = "manager"
                        },
                        new
                        {
                            Id = "USR003",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 622, DateTimeKind.Utc).AddTicks(611),
                            Email = "employee1@stationcheck.com",
                            FullName = "Nhân viên Trạm 1",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$12$9AYUVelqsF1udUEGX/OATuvhdgUoE1wPenTl0CAF88wu0c9BSm6r.",
                            Role = 0,
                            StationId = 1,
                            Username = "employee1"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.ConfigurationAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Changes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ConfigurationAuditLogs");
                });

            modelBuilder.Entity("StationCheck.Models.EmailEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AlarmDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlarmEvent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlarmInputChannelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AlarmInputChannelNo")
                        .HasColumnType("int");

                    b.Property<string>("AlarmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("AlarmStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EmailReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("RawEmailBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailReceivedAt");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("StationCode");

                    b.HasIndex("StationId");

                    b.ToTable("EmailEvents");
                });

            modelBuilder.Entity("StationCheck.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagIcon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("IsDefault");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "vi",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2059),
                            FlagIcon = "vn",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Vietnamese",
                            NativeName = "Tiếng Việt"
                        },
                        new
                        {
                            Code = "en",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2061),
                            FlagIcon = "us",
                            IsActive = true,
                            IsDefault = false,
                            Name = "English",
                            NativeName = "English"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StationId");

                    b.ToTable("MonitoringConfiguration");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonitoringProfile");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfileHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MonitoringProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringProfileId");

                    b.ToTable("MonitoringProfileHistory");
                });

            modelBuilder.Entity("StationCheck.Models.MotionAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AlertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationSnapshot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExpectedFrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMotionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMotionCameraId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastMotionCameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MinutesSinceLastMotion")
                        .HasColumnType("int");

                    b.Property<int?>("MonitoringConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProfileHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TimeFrameHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeFrameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlertTime");

                    b.HasIndex("CameraId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("MonitoringConfigurationId");

                    b.HasIndex("ProfileHistoryId");

                    b.HasIndex("Severity");

                    b.HasIndex("StationId");

                    b.HasIndex("TimeFrameHistoryId");

                    b.HasIndex("TimeFrameId");

                    b.ToTable("MotionAlerts");
                });

            modelBuilder.Entity("StationCheck.Models.MotionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SnapshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("StationId");

                    b.ToTable("MotionEvents");
                });

            modelBuilder.Entity("StationCheck.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StationCheck.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMotionDetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Quận Hoàn Kiếm, Hà Nội",
                            ContactPerson = "Nguyễn Văn A",
                            ContactPhone = "0123456789",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 6, 617, DateTimeKind.Utc).AddTicks(7016),
                            Description = "Trạm quan trắc chất lượng nước sông Hồng",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Trạm Quan Trắc Sông Hồng",
                            StationCode = "123123123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Quận Đống Đa, Hà Nội",
                            ContactPerson = "Trần Thị B",
                            ContactPhone = "0987654321",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 6, 617, DateTimeKind.Utc).AddTicks(7020),
                            Description = "Trạm quan trắc chất lượng nước sông Tô Lịch",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Trạm Quan Trắc Sông Tô Lịch",
                            StationCode = "121123123"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(8068),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian quét email mới (giây)",
                            DisplayName = "Email Monitor Interval",
                            IsEditable = true,
                            Key = "EmailMonitorInterval",
                            Value = "180",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 2,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(8070),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian kiểm tra và tạo cảnh báo (giây)",
                            DisplayName = "Alert Generation Interval",
                            IsEditable = true,
                            Key = "AlertGenerationInterval",
                            Value = "3600",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(8072),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian kiểm tra chuyển động (giây)",
                            DisplayName = "Motion Monitor Interval",
                            IsEditable = true,
                            Key = "MotionMonitorInterval",
                            Value = "60",
                            ValueType = "int"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StationId");

                    b.ToTable("TimeFrames");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeFrameId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("StationId");

                    b.HasIndex("TimeFrameId");

                    b.HasIndex("TimeFrameId", "Version")
                        .IsUnique()
                        .HasFilter("[TimeFrameId] IS NOT NULL");

                    b.ToTable("TimeFrameHistories");
                });

            modelBuilder.Entity("StationCheck.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("LanguageCode", "Key")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2088),
                            Key = "menu.dashboard",
                            LanguageCode = "vi",
                            Value = "Trang chủ"
                        },
                        new
                        {
                            Id = 2,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2090),
                            Key = "menu.stations",
                            LanguageCode = "vi",
                            Value = "Quản lý Trạm"
                        },
                        new
                        {
                            Id = 3,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2092),
                            Key = "menu.users",
                            LanguageCode = "vi",
                            Value = "Quản lý User"
                        },
                        new
                        {
                            Id = 4,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2093),
                            Key = "menu.settings",
                            LanguageCode = "vi",
                            Value = "Cấu hình"
                        },
                        new
                        {
                            Id = 5,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2095),
                            Key = "button.add",
                            LanguageCode = "vi",
                            Value = "Thêm mới"
                        },
                        new
                        {
                            Id = 6,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2096),
                            Key = "button.edit",
                            LanguageCode = "vi",
                            Value = "Chỉnh sửa"
                        },
                        new
                        {
                            Id = 7,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2098),
                            Key = "button.delete",
                            LanguageCode = "vi",
                            Value = "Xóa"
                        },
                        new
                        {
                            Id = 8,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2099),
                            Key = "button.save",
                            LanguageCode = "vi",
                            Value = "Lưu"
                        },
                        new
                        {
                            Id = 9,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2101),
                            Key = "button.cancel",
                            LanguageCode = "vi",
                            Value = "Hủy"
                        },
                        new
                        {
                            Id = 10,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2107),
                            Key = "station.name",
                            LanguageCode = "vi",
                            Value = "Tên trạm"
                        },
                        new
                        {
                            Id = 11,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2109),
                            Key = "station.address",
                            LanguageCode = "vi",
                            Value = "Địa chỉ"
                        },
                        new
                        {
                            Id = 12,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2110),
                            Key = "station.contact",
                            LanguageCode = "vi",
                            Value = "Người liên hệ"
                        },
                        new
                        {
                            Id = 13,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2112),
                            Key = "station.phone",
                            LanguageCode = "vi",
                            Value = "Số điện thoại"
                        },
                        new
                        {
                            Id = 14,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2113),
                            Key = "station.page_title",
                            LanguageCode = "vi",
                            Value = "Quản lý Trạm"
                        },
                        new
                        {
                            Id = 15,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2115),
                            Key = "station.list_title",
                            LanguageCode = "vi",
                            Value = "Danh sách Trạm Quan Trắc"
                        },
                        new
                        {
                            Id = 16,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2116),
                            Key = "station.add_button",
                            LanguageCode = "vi",
                            Value = "Thêm Trạm Mới"
                        },
                        new
                        {
                            Id = 17,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2118),
                            Key = "station.edit_title_add",
                            LanguageCode = "vi",
                            Value = "Thêm Trạm Mới"
                        },
                        new
                        {
                            Id = 18,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2119),
                            Key = "station.edit_title_edit",
                            LanguageCode = "vi",
                            Value = "Chỉnh sửa Trạm"
                        },
                        new
                        {
                            Id = 19,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2121),
                            Key = "station.search_placeholder",
                            LanguageCode = "vi",
                            Value = "Tìm kiếm..."
                        },
                        new
                        {
                            Id = 20,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2122),
                            Key = "station.name_column",
                            LanguageCode = "vi",
                            Value = "Tên Trạm"
                        },
                        new
                        {
                            Id = 21,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2124),
                            Key = "station.address_column",
                            LanguageCode = "vi",
                            Value = "Địa chỉ"
                        },
                        new
                        {
                            Id = 22,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2125),
                            Key = "station.contact_column",
                            LanguageCode = "vi",
                            Value = "Người liên hệ"
                        },
                        new
                        {
                            Id = 23,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2127),
                            Key = "station.phone_column",
                            LanguageCode = "vi",
                            Value = "Số điện thoại"
                        },
                        new
                        {
                            Id = 24,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2128),
                            Key = "station.actions_column",
                            LanguageCode = "vi",
                            Value = "Thao tác"
                        },
                        new
                        {
                            Id = 25,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2130),
                            Key = "station.name_label",
                            LanguageCode = "vi",
                            Value = "Tên Trạm:"
                        },
                        new
                        {
                            Id = 26,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2131),
                            Key = "station.address_label",
                            LanguageCode = "vi",
                            Value = "Địa chỉ:"
                        },
                        new
                        {
                            Id = 27,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2133),
                            Key = "station.description_label",
                            LanguageCode = "vi",
                            Value = "Mô tả:"
                        },
                        new
                        {
                            Id = 28,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2134),
                            Key = "station.contact_label",
                            LanguageCode = "vi",
                            Value = "Người liên hệ:"
                        },
                        new
                        {
                            Id = 29,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2136),
                            Key = "station.phone_label",
                            LanguageCode = "vi",
                            Value = "Số điện thoại:"
                        },
                        new
                        {
                            Id = 30,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2137),
                            Key = "station.active_label",
                            LanguageCode = "vi",
                            Value = "Kích hoạt giám sát:"
                        },
                        new
                        {
                            Id = 31,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2139),
                            Key = "message.confirm_delete_station",
                            LanguageCode = "vi",
                            Value = "Bạn có chắc muốn xóa trạm này?"
                        },
                        new
                        {
                            Id = 32,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2140),
                            Key = "message.delete_error",
                            LanguageCode = "vi",
                            Value = "Không thể xóa"
                        },
                        new
                        {
                            Id = 33,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2142),
                            Key = "message.error",
                            LanguageCode = "vi",
                            Value = "Lỗi"
                        },
                        new
                        {
                            Id = 101,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2143),
                            Key = "menu.dashboard",
                            LanguageCode = "en",
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = 102,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2145),
                            Key = "menu.stations",
                            LanguageCode = "en",
                            Value = "Station Management"
                        },
                        new
                        {
                            Id = 103,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2146),
                            Key = "menu.users",
                            LanguageCode = "en",
                            Value = "User Management"
                        },
                        new
                        {
                            Id = 104,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2148),
                            Key = "menu.settings",
                            LanguageCode = "en",
                            Value = "Settings"
                        },
                        new
                        {
                            Id = 105,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2149),
                            Key = "button.add",
                            LanguageCode = "en",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 106,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2151),
                            Key = "button.edit",
                            LanguageCode = "en",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 107,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2152),
                            Key = "button.delete",
                            LanguageCode = "en",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 108,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2154),
                            Key = "button.save",
                            LanguageCode = "en",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 109,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2155),
                            Key = "button.cancel",
                            LanguageCode = "en",
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = 110,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2157),
                            Key = "station.name",
                            LanguageCode = "en",
                            Value = "Station Name"
                        },
                        new
                        {
                            Id = 111,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2158),
                            Key = "station.address",
                            LanguageCode = "en",
                            Value = "Address"
                        },
                        new
                        {
                            Id = 112,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2160),
                            Key = "station.contact",
                            LanguageCode = "en",
                            Value = "Contact Person"
                        },
                        new
                        {
                            Id = 113,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2161),
                            Key = "station.phone",
                            LanguageCode = "en",
                            Value = "Phone Number"
                        },
                        new
                        {
                            Id = 114,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2163),
                            Key = "station.page_title",
                            LanguageCode = "en",
                            Value = "Station Management"
                        },
                        new
                        {
                            Id = 115,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2166),
                            Key = "station.list_title",
                            LanguageCode = "en",
                            Value = "Monitoring Station List"
                        },
                        new
                        {
                            Id = 116,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2167),
                            Key = "station.add_button",
                            LanguageCode = "en",
                            Value = "Add New Station"
                        },
                        new
                        {
                            Id = 117,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2169),
                            Key = "station.edit_title_add",
                            LanguageCode = "en",
                            Value = "Add New Station"
                        },
                        new
                        {
                            Id = 118,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2170),
                            Key = "station.edit_title_edit",
                            LanguageCode = "en",
                            Value = "Edit Station"
                        },
                        new
                        {
                            Id = 119,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2172),
                            Key = "station.search_placeholder",
                            LanguageCode = "en",
                            Value = "Search..."
                        },
                        new
                        {
                            Id = 120,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2173),
                            Key = "station.name_column",
                            LanguageCode = "en",
                            Value = "Station Name"
                        },
                        new
                        {
                            Id = 121,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2175),
                            Key = "station.address_column",
                            LanguageCode = "en",
                            Value = "Address"
                        },
                        new
                        {
                            Id = 122,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2176),
                            Key = "station.contact_column",
                            LanguageCode = "en",
                            Value = "Contact Person"
                        },
                        new
                        {
                            Id = 123,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2178),
                            Key = "station.phone_column",
                            LanguageCode = "en",
                            Value = "Phone Number"
                        },
                        new
                        {
                            Id = 124,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2179),
                            Key = "station.actions_column",
                            LanguageCode = "en",
                            Value = "Actions"
                        },
                        new
                        {
                            Id = 125,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2181),
                            Key = "station.name_label",
                            LanguageCode = "en",
                            Value = "Station Name:"
                        },
                        new
                        {
                            Id = 126,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2182),
                            Key = "station.address_label",
                            LanguageCode = "en",
                            Value = "Address:"
                        },
                        new
                        {
                            Id = 127,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2184),
                            Key = "station.description_label",
                            LanguageCode = "en",
                            Value = "Description:"
                        },
                        new
                        {
                            Id = 128,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2185),
                            Key = "station.contact_label",
                            LanguageCode = "en",
                            Value = "Contact Person:"
                        },
                        new
                        {
                            Id = 129,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2187),
                            Key = "station.phone_label",
                            LanguageCode = "en",
                            Value = "Phone Number:"
                        },
                        new
                        {
                            Id = 130,
                            Category = "label",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2188),
                            Key = "station.active_label",
                            LanguageCode = "en",
                            Value = "Enable Monitoring:"
                        },
                        new
                        {
                            Id = 131,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2190),
                            Key = "message.confirm_delete_station",
                            LanguageCode = "en",
                            Value = "Are you sure you want to delete this station?"
                        },
                        new
                        {
                            Id = 132,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2191),
                            Key = "message.delete_error",
                            LanguageCode = "en",
                            Value = "Cannot delete"
                        },
                        new
                        {
                            Id = 133,
                            Category = "message",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 12, 7, 625, DateTimeKind.Utc).AddTicks(2193),
                            Key = "message.error",
                            LanguageCode = "en",
                            Value = "Error"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.ApplicationUser", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StationCheck.Models.Station", null)
                        .WithMany("StationEmployees")
                        .HasForeignKey("StationId1");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.EmailEvent", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringConfiguration", b =>
                {
                    b.HasOne("StationCheck.Models.MonitoringProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Profile");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfileHistory", b =>
                {
                    b.HasOne("StationCheck.Models.MonitoringProfile", "MonitoringProfile")
                        .WithMany("History")
                        .HasForeignKey("MonitoringProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringProfile");
                });

            modelBuilder.Entity("StationCheck.Models.MotionAlert", b =>
                {
                    b.HasOne("StationCheck.Models.MonitoringConfiguration", "MonitoringConfiguration")
                        .WithMany()
                        .HasForeignKey("MonitoringConfigurationId");

                    b.HasOne("StationCheck.Models.MonitoringProfileHistory", "ProfileHistory")
                        .WithMany("GeneratedAlerts")
                        .HasForeignKey("ProfileHistoryId");

                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StationCheck.Models.TimeFrameHistory", "TimeFrameHistorySnapshot")
                        .WithMany()
                        .HasForeignKey("TimeFrameHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StationCheck.Models.TimeFrame", "TimeFrame")
                        .WithMany()
                        .HasForeignKey("TimeFrameId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonitoringConfiguration");

                    b.Navigation("ProfileHistory");

                    b.Navigation("Station");

                    b.Navigation("TimeFrame");

                    b.Navigation("TimeFrameHistorySnapshot");
                });

            modelBuilder.Entity("StationCheck.Models.MotionEvent", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.RefreshToken", b =>
                {
                    b.HasOne("StationCheck.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrame", b =>
                {
                    b.HasOne("StationCheck.Models.MonitoringProfile", "Profile")
                        .WithMany("TimeFrames")
                        .HasForeignKey("ProfileId");

                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany("TimeFrames")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrameHistory", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StationCheck.Models.TimeFrame", "TimeFrame")
                        .WithMany()
                        .HasForeignKey("TimeFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");

                    b.Navigation("TimeFrame");
                });

            modelBuilder.Entity("StationCheck.Models.Translation", b =>
                {
                    b.HasOne("StationCheck.Models.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("StationCheck.Models.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfile", b =>
                {
                    b.Navigation("History");

                    b.Navigation("TimeFrames");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfileHistory", b =>
                {
                    b.Navigation("GeneratedAlerts");
                });

            modelBuilder.Entity("StationCheck.Models.Station", b =>
                {
                    b.Navigation("StationEmployees");

                    b.Navigation("TimeFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
