// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationCheck.Data;

#nullable disable

namespace StationCheck.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationCheck.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("StationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "USR001",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9230),
                            Email = "admin@stationcheck.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$12$PdJYccmRTUBakyXhyWwxWOfkMLQiLvSJnGmIP7H/U3kiY66uh5tAi",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = "USR002",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9237),
                            Email = "manager@stationcheck.com",
                            FullName = "Department Manager",
                            IsActive = true,
                            PasswordHash = "$2a$12$sQAmK/m23FnnNKYhP9KGcOOkd6TsEKoB.ZADChyJdK8XBQhgP683S",
                            Role = 1,
                            Username = "manager"
                        },
                        new
                        {
                            Id = "USR003",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9251),
                            CreatedBy = "System",
                            Email = "employee1@stationcheck.com",
                            FullName = "Nhân viên Trạm 1",
                            IsActive = true,
                            PasswordHash = "$2a$12$zXBPTAySnQ/y2W8alLuzeO0Nqgp8ZGN8TS3uhGwBAp8mEPvFsRKNi",
                            Role = 0,
                            StationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Username = "employee1"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.EmailEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AlarmDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlarmEvent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlarmInputChannelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AlarmInputChannelNo")
                        .HasColumnType("int");

                    b.Property<string>("AlarmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("AlarmStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EmailReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawEmailBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmailReceivedAt");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("StationCode");

                    b.HasIndex("StationId");

                    b.ToTable("EmailEvents");
                });

            modelBuilder.Entity("StationCheck.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FlagIcon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("IsDefault");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "vi",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9385),
                            CreatedBy = "System",
                            FlagIcon = "vn",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Vietnamese",
                            NativeName = "Tiếng Việt"
                        },
                        new
                        {
                            Code = "en",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9388),
                            CreatedBy = "System",
                            FlagIcon = "us",
                            IsActive = true,
                            IsDefault = false,
                            Name = "English",
                            NativeName = "English"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("MonitoringProfile");
                });

            modelBuilder.Entity("StationCheck.Models.MotionAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AlertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CameraId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationSnapshot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExpectedFrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMotionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMotionCameraId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastMotionCameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MinutesSinceLastMotion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TimeFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlertTime");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.HasIndex("StationId");

                    b.HasIndex("TimeFrameId");

                    b.ToTable("MotionAlerts");
                });

            modelBuilder.Entity("StationCheck.Models.MotionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SnapshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("StationId");

                    b.ToTable("MotionEvents");
                });

            modelBuilder.Entity("StationCheck.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMotionDetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Quận Hoàn Kiếm, Hà Nội",
                            ContactPerson = "Nguyễn Văn A",
                            ContactPhone = "0123456789",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 6, 507, DateTimeKind.Utc).AddTicks(1003),
                            CreatedBy = "System",
                            Description = "Trạm quan trắc chất lượng nước sông Hồng",
                            IsActive = true,
                            Name = "Trạm Quan Trắc Sông Hồng",
                            StationCode = "SH01"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Quận Đống Đa, Hà Nội",
                            ContactPerson = "Trần Thị B",
                            ContactPhone = "0987654321",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 6, 507, DateTimeKind.Utc).AddTicks(1006),
                            CreatedBy = "System",
                            Description = "Trạm quan trắc chất lượng nước sông Tô Lịch",
                            IsActive = true,
                            Name = "Trạm Quan Trắc Sông Tô Lịch",
                            StationCode = "TL01"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.StationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("StationId");

                    b.ToTable("StationHistories");
                });

            modelBuilder.Entity("StationCheck.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 382, DateTimeKind.Utc).AddTicks(204),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian quét email mới (giây)",
                            DisplayName = "Email Monitor Interval",
                            IsEditable = true,
                            Key = "EmailMonitorInterval",
                            Value = "180",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 2,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 382, DateTimeKind.Utc).AddTicks(208),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian kiểm tra và tạo cảnh báo (giây)",
                            DisplayName = "Alert Generation Interval",
                            IsEditable = true,
                            Key = "AlertGenerationInterval",
                            Value = "3600",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3,
                            Category = "BackgroundServices",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 382, DateTimeKind.Utc).AddTicks(211),
                            CreatedBy = "System",
                            Description = "Khoảng thời gian kiểm tra chuyển động (giây)",
                            DisplayName = "Motion Monitor Interval",
                            IsEditable = true,
                            Key = "MotionMonitorInterval",
                            Value = "60",
                            ValueType = "int"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StationId");

                    b.ToTable("TimeFrames");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TimeFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("StationId");

                    b.HasIndex("TimeFrameId");

                    b.HasIndex("TimeFrameId", "Version")
                        .IsUnique()
                        .HasFilter("[TimeFrameId] IS NOT NULL");

                    b.ToTable("TimeFrameHistories");
                });

            modelBuilder.Entity("StationCheck.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("LanguageCode", "Key")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9406),
                            CreatedBy = "System",
                            Key = "menu.dashboard",
                            LanguageCode = "vi",
                            Value = "Trang chủ"
                        },
                        new
                        {
                            Id = 2,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9408),
                            CreatedBy = "System",
                            Key = "menu.stations",
                            LanguageCode = "vi",
                            Value = "Quản lý Trạm"
                        },
                        new
                        {
                            Id = 3,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9410),
                            CreatedBy = "System",
                            Key = "button.add",
                            LanguageCode = "vi",
                            Value = "Thêm mới"
                        },
                        new
                        {
                            Id = 101,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9412),
                            CreatedBy = "System",
                            Key = "menu.dashboard",
                            LanguageCode = "en",
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = 102,
                            Category = "menu",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9415),
                            CreatedBy = "System",
                            Key = "menu.stations",
                            LanguageCode = "en",
                            Value = "Station Management"
                        },
                        new
                        {
                            Id = 103,
                            Category = "button",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 30, 7, 381, DateTimeKind.Utc).AddTicks(9417),
                            CreatedBy = "System",
                            Key = "button.add",
                            LanguageCode = "en",
                            Value = "Add New"
                        });
                });

            modelBuilder.Entity("StationCheck.Models.ApplicationUser", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.EmailEvent", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.MonitoringProfile", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.MotionAlert", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StationCheck.Models.TimeFrame", "TimeFrame")
                        .WithMany()
                        .HasForeignKey("TimeFrameId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Station");

                    b.Navigation("TimeFrame");
                });

            modelBuilder.Entity("StationCheck.Models.MotionEvent", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.StationHistory", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrame", b =>
                {
                    b.HasOne("StationCheck.Models.MonitoringProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany("TimeFrames")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationCheck.Models.TimeFrameHistory", b =>
                {
                    b.HasOne("StationCheck.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationCheck.Models.TimeFrame", "TimeFrame")
                        .WithMany()
                        .HasForeignKey("TimeFrameId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Station");

                    b.Navigation("TimeFrame");
                });

            modelBuilder.Entity("StationCheck.Models.Translation", b =>
                {
                    b.HasOne("StationCheck.Models.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("StationCheck.Models.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("StationCheck.Models.Station", b =>
                {
                    b.Navigation("TimeFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
