using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StationCheck.Models
{
    /// <summary>
    /// Stores historical versions of MonitoringProfiles for audit trail
    /// When a profile is updated, a snapshot is saved here with incremented version
    /// </summary>
    public class MonitoringProfileHistory
    {
        [Key]
        public Guid Id { get; set; }

        // Link to the current/active profile
        public Guid MonitoringProfileId { get; set; }
        
        [ForeignKey(nameof(MonitoringProfileId))]
        public MonitoringProfile? MonitoringProfile { get; set; }

        // Version number (incremental: 1, 2, 3, ...)
        [Required]
        public int Version { get; set; }

        // Snapshot of profile data at this version (JSON)
        [Required]
        [MaxLength(4000)]
        public string ProfileSnapshot { get; set; } = string.Empty;

        // Who made the change
        [MaxLength(100)]
        public string? ModifiedBy { get; set; }

        // When this version was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Change description/notes
        [MaxLength(1000)]
        public string? ChangeNotes { get; set; }

        // Navigation: All alerts generated by this profile version
        public ICollection<MotionAlert> GeneratedAlerts { get; set; } = new List<MotionAlert>();
    }
}
